openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    <опис вашого додатку>
tags:
  # теги, що ви будете використовувати
servers:
  - url: http://localhost:14000
  - url: #посилання на задеплоєний сайт
paths:
  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{contactId}/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
