openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    <опис вашого додатку>
tags:
  - name: auth
    description: Endpoints related to user authentication
  - name: contacts
    description: Endpoints related to managing contacts
servers:
  - url: http://localhost:14000
  - url: https://nodejs-hw-mongodb-lc59.onrender.com
paths:
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login/post.yaml
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register/post.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh/post.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout/post.yaml
  /auth/send-reset-email:
    post:
      $ref: ../swagger/paths/auth/send-reset-email/post.yaml
  /auth/reset-pwd:
    post:
      $ref: ../swagger/paths/auth/reset-pwd/post.yaml
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{contactId}:
    patch:
      $ref: ../swagger/paths/contacts/{contactId}/patch.yaml
    get:
      $ref: ../swagger/paths/contacts/{contactId}/get.yaml
    delete:
      $ref: ../swagger/paths/contacts/{contactId}/delete.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
